### ISSUE TITLE
zstash create --include mode?

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/zstash#248] opened 2023-01-21 01:08 UTC
`zstash create --exclude` is very handy. It would be nice to also have a `zstash create --include` option. 

For example, for the 50 TB per simulated month SCREAM runs I'm doing, I want to be able to zstash all the "T_2m" files together without also having to zstash a bunch of other files (which are individually 200 GB to 2 TB in size).

**Comment by forsyth2** [comment] 2023-01-21 01:27
Closing as duplicate of #199. Thanks for the comment; I copied it over.

**Closed by forsyth2** 2023-01-21 01:27 UTC
