### ISSUE TITLE
Duplicated file fullpathnames with different checksums

### ISSUE THREAD

**Issue by TonyB9000** [E3SM-Project/zstash#74] opened 2020-05-08 16:47 UTC
I have seen duplicated tar files (full paths) once before, and assumed it was just a harmless listing issue, but this second time I have confirmed, using "zstash ls -l", that the duplications have different checksums.  This renders extraction (potentially) unpredictable.  Two archives exhibit this.

The archives in question are:  
/p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRC_CNPECACNT_20TR.ne30_oECv3.cori-knl 
/p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRD_CNPECACNT_20TR.ne30_oECv3.cori-knl

For the first set, it is the 2014 monthly
    (ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-02-01_00.00.00.nc)
for all months except January.  The "original" set appears to be in the 000001.tar file, and the duplicates-in-name appear in the 000004.tar and 000005.tar files.  The "ls -l" output is given below.

For the second set, it appears to be the first 8 months of 2011, and January 2014 that have this duplication problem.  

I am guessing that this feature is an artifact of the "zstash update" command, and (hopefully) zstash would know to extract only the latest of duplicates (assuming that was the author's intention).  Ideally, an "update" would render the previous match un-listable as well as un-extractable.  In any case, the "zstash update --help" gives no indication of the expected behavior when applied to either new (append) or existing (replace) material.

In the first case above, with (assumed) originals in 000001.tar, and the later duplicates elsewhere, would anyone who copied over only the 000001.tar and index.db, and attempted extraction of just one duplicated file receive 

1. the original file, because it was the only one available?
2. an error message that tarfiles are missing?
3. a reply that there is no such file (referring only to the latest) in the archive?

(When I have the time, I will conduct such an experiment, with a simulated archive where the "zstash" subdirectory contains only symlinks to 000001.tar and the index.db file.)

I will contact the author (Jinyun) for insight, and perhaps revised archives.

Here is the "zstash ls -l" output from the first archive.

        **ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-02-01_00.00.00.nc**       151551336       2019-05-25 10:35:38     **ec7214db895b6f4dd91d333ee15b6c8d**        000001.tar      111445023744
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-03-01_00.00.00.nc       181651888       2019-05-25 11:18:12     cd8d46eff4f742eccd28f7f74a841482        000001.tar      111596575744
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-04-01_00.00.00.nc       181651888       2019-05-25 11:59:56     937c585eee7abb5c64b59979e41b9e20        000001.tar      111778228224
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-05-01_00.00.00.nc       211752440       2019-05-25 12:48:55     046349d6499bd8346fa42c62198bd8a6        000001.tar      111959880704
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-06-01_00.00.00.nc       181651888       2019-05-25 13:31:19     2f6b7e8e893b58fc4deb7b74701a2a15        000001.tar      112171633664
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-07-01_00.00.00.nc       181651888       2019-05-25 14:14:52     332448a6e3a71ca0ea699cdbf835df4d        000001.tar      112353286144
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-08-01_00.00.00.nc       181651888       2019-05-25 14:56:59     1219cef89654ea992df7a4a52cc67fd0        000001.tar      112534938624
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-09-01_00.00.00.nc       181651888       2019-05-25 15:39:08     6e9652c1485e3b081681f25c688c79d1        000001.tar      112716591104
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-10-01_00.00.00.nc       181651888       2019-05-25 16:20:57     5195c4073a802259f0d4310a3b55f476        000001.tar      112898243584
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-11-01_00.00.00.nc       181651888       2019-05-25 17:02:41     4b1d1686fd5c2e3be97162451a13bcb7        000001.tar      113079896064
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-12-01_00.00.00.nc       91350232        2019-05-25 17:23:52     9d1700b296b0e8cf0020d54121fc5179        000001.tar      113261548544
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-01-01_00.00.00.nc       181651888       2019-05-26 05:29:58     977dd44e3cdb5d4b488ad882a4edb87f        000004.tar      23265457664
        **ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-02-01_00.00.00.nc**       151551336       2019-05-26 06:09:37     **e006c58cf60325e4138f2e2ed374fc76**        000004.tar      23447110144
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-03-01_00.00.00.nc       181651888       2019-05-26 06:59:09     f5812aa6ae3790eec34accf16c33e50f        000004.tar      23598662144
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-04-01_00.00.00.nc       181651888       2019-05-26 07:49:17     54d2e47b33c97a18005bb8aafea4b475        000004.tar      23780314624
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-05-01_00.00.00.nc       211752440       2019-05-26 08:44:12     d67887cec712e91254ae3098ad20e6d2        000004.tar      23961967104
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-06-01_00.00.00.nc       181651888       2019-05-26 09:32:19     f0567a0545176ef2aaaebd45f31108f5        000004.tar      24173720064
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-07-01_00.00.00.nc       181651888       2019-05-26 17:03:12     2d5396e7968b0baac9bbb1124bccc341        000005.tar      23480672256
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-08-01_00.00.00.nc       181651888       2019-05-26 17:49:11     61dc0a2bf2f7fa93de3be74cfd474316        000005.tar      23662324736
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-09-01_00.00.00.nc       181651888       2019-05-26 18:36:37     3c60a6a6bb6f5ef416df98cb513244dc        000005.tar      23843977216
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-10-01_00.00.00.nc       181651888       2019-05-26 19:23:20     44b7414c49fb24fdbc0d3361800ebfce        000005.tar      24025629696
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-11-01_00.00.00.nc       181651888       2019-05-26 20:11:34     d18480e90708b26cab70ca3c1300fcc2        000005.tar      24207282176
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-12-01_00.00.00.nc       181651888       2019-05-26 20:59:13     133d29424454569fc4f8d3eef11cbc4b        000005.tar      24388934656
        ocn/hist/mpaso.hist.am.highFrequencyOutput.2015-01-01_00.00.00.nc       31149128        2019-05-26 21:07:15     b8edbb9c0adaa724838253973b43b7ad        000005.tar      24570587136

        Conclusion:  For the archive:  /p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRC_CNPECACNT_20TR.ne30_oECv3.cori-knl
                     Identically-named files (with SAME tar-path) appear in different tar-files, but with different checksums.

**Comment by TonyB9000** [comment] 2020-05-08 18:07
The experiment was encouraging.  Only the "updated" version (latest mtime?) of a duplicated file is extracted, and if that tarfile is missing, an error is thrown.

My Test:

(base) -bash-4.1$ ./archive_holodeck_setup.sh /p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRC_CNPECACNT_20TR.ne30_oECv3.cori-knl
Clearing the Holodeck

We will setup holodeck zstash for directory /p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRC_CNPECACNT_20TR.ne30_oECv3.cori-knl
Holodeck prepared for entry. Enjoy your simulation!
(base) -bash-4.1$ cd Holodeck
(base) -bash-4.1$ ll
total 0
drwxr-x--- 2 bartoletti1 climate 4096 May  8 10:34 zstash
(base) -bash-4.1$ mkdir hold
(base) -bash-4.1$ ll zstash/
total 0
lrwxrwxrwx 1 bartoletti1 climate 87 May  8 10:34 000000.tar -> /p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRC_CNPECACNT_20TR.ne30_oECv3.cori-knl/000000.tar
lrwxrwxrwx 1 bartoletti1 climate 87 May  8 10:34 000001.tar -> /p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRC_CNPECACNT_20TR.ne30_oECv3.cori-knl/000001.tar
lrwxrwxrwx 1 bartoletti1 climate 87 May  8 10:34 000002.tar -> /p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRC_CNPECACNT_20TR.ne30_oECv3.cori-knl/000002.tar
lrwxrwxrwx 1 bartoletti1 climate 87 May  8 10:34 000003.tar -> /p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRC_CNPECACNT_20TR.ne30_oECv3.cori-knl/000003.tar
lrwxrwxrwx 1 bartoletti1 climate 87 May  8 10:34 000004.tar -> /p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRC_CNPECACNT_20TR.ne30_oECv3.cori-knl/000004.tar
lrwxrwxrwx 1 bartoletti1 climate 87 May  8 10:34 000005.tar -> /p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRC_CNPECACNT_20TR.ne30_oECv3.cori-knl/000005.tar
lrwxrwxrwx 1 bartoletti1 climate 85 May  8 10:34 index.db -> /p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRC_CNPECACNT_20TR.ne30_oECv3.cori-knl/index.db
(base) -bash-4.1$ mv zstash/000004.tar hold
(base) -bash-4.1$ ll zstash/
total 0
lrwxrwxrwx 1 bartoletti1 climate 87 May  8 10:34 000000.tar -> /p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRC_CNPECACNT_20TR.ne30_oECv3.cori-knl/000000.tar
lrwxrwxrwx 1 bartoletti1 climate 87 May  8 10:34 000001.tar -> /p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRC_CNPECACNT_20TR.ne30_oECv3.cori-knl/000001.tar
lrwxrwxrwx 1 bartoletti1 climate 87 May  8 10:34 000002.tar -> /p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRC_CNPECACNT_20TR.ne30_oECv3.cori-knl/000002.tar
lrwxrwxrwx 1 bartoletti1 climate 87 May  8 10:34 000003.tar -> /p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRC_CNPECACNT_20TR.ne30_oECv3.cori-knl/000003.tar
lrwxrwxrwx 1 bartoletti1 climate 87 May  8 10:34 000005.tar -> /p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRC_CNPECACNT_20TR.ne30_oECv3.cori-knl/000005.tar
lrwxrwxrwx 1 bartoletti1 climate 85 May  8 10:34 index.db -> /p/user_pub/e3sm/archive/1_1_ECA/BGC/BCRC_CNPECACNT_20TR.ne30_oECv3.cori-knl/index.db
(base) -bash-4.1$ zstash extract --hpss=none ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-02-01_00.00.00.nc
INFO: get: HPSS is unavailable
INFO: Opening tar archive zstash/000004.tar
Traceback (most recent call last):
  File "/export/bartoletti1/anaconda3/bin/zstash", line 8, in <module>
    sys.exit(main())
  File "/export/bartoletti1/anaconda3/lib/python3.7/site-packages/zstash/main.py", line 47, in main
    extract()
  File "/export/bartoletti1/anaconda3/lib/python3.7/site-packages/zstash/extract.py", line 194, in extract
    failures = extractFiles(matches, keep_files, config.keep)
  File "/export/bartoletti1/anaconda3/lib/python3.7/site-packages/zstash/extract.py", line 286, in extractFiles
    tar = tarfile.open(tfname, "r")
  File "/export/bartoletti1/anaconda3/lib/python3.7/tarfile.py", line 1573, in open
    return func(name, "r", fileobj, **kwargs)
  File "/export/bartoletti1/anaconda3/lib/python3.7/tarfile.py", line 1638, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/export/bartoletti1/anaconda3/lib/python3.7/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'zstash/000004.tar'
(base) -bash-4.1$ zstash ls -l --hpss=none ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-02*
id      name    size    mtime   md5     tar     offset
1172    ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-02-01_00.00.00.nc       151551336       2019-05-25 10:35:38     ec7214db895b6f4dd91d333ee15b6c8d        000001.tar      111445023744
1738    ocn/hist/mpaso.hist.am.highFrequencyOutput.2014-02-01_00.00.00.nc       151551336       2019-05-26 06:09:37     e006c58cf60325e4138f2e2ed374fc76        000004.tar      23447110144

I do feel that this behavior should be made explicit in the help text.  E.g.  "In the event that an update includes revisions to files previously zstash-archived, only the latest ["latest zstashed?"  "latest mtime?"] will be accessible for extraction.  All file versions will still be listed with the "ls" and "ls -l" commands."

Another experiment to conduct:
1.  Create a "correct" file X, place it in "hold-date1/"
2.  Create an "incorrect revision" X, place it in "hold-date2/"
(much later)
3.  move hold-date2/X to "staging/", add to zstash archive.
4.  realize your mistake, move hold-date1/X to "staging/", update to zstash

Upon zstash extract X. which X will be extracted?
- the correct (original) one, because it was the latest to be zstashed?
- the incorrect one, because it had the latest mtime?

**Comment by golaz** [comment] 2021-02-19 18:20
@TonyB9000, by design, zstash is a write-only archive with no option for deletion. This is because files are stored in tar files, and deleting a file would require recreating the tar file. Properly handling this would greatly complicate zstash.

However, the case you mentioned before was considered when zstash was created. If a file is updated after zstash create, zstash update will archive the new version, which is what a user would expect to happen. The database and tar files will include both versions of the file and zstash ls will list both. However, zstash extract will only extract the most recently archived version of the file, again this is what a user would expect. Here is the code to do this:

https://github.com/E3SM-Project/zstash/blob/77aa3f54f8f7de9670ff957ac71b6085e4db154a/zstash/extract.py#L177-L189

If a user really needs to extract a previous version, this can be accomplished by locating the tar file using zstash ls and then manually extracting it from the tar file (`tar xcf 000001.tar myfile.txt`). We could regard this a a bonus feature of zstash in the sense that it does allow a user to recover previous file versions if they accidentally got overwritten.

**Comment by TonyB9000** [comment] 2021-02-19 19:25
@golaz, I understand why the archive itself cannot be modified (except appended to), given their size.  Also, I'm glad to learn that only the "last archived" is extracted (by zstash), and not the file with the "last mtime", for instance. 

But if "zstash extract" will only _extract_ the last file archived, then "zstash ls -l" should only _list_ the last file archived.  

I note that zstash ls -l gives {id      name    size    mtime   md5     tar     offset}.  I assume one must infer that "id" corresponds to the archive sequence, and (for duplicated filename) "latest" is the one with the greatest id.  I know this was an unusual circumstance, but would be nice to document this behavior.  I was unaware.

**Comment by golaz** [comment] 2021-02-19 22:00
@TonyB9000 : zstash will extract the latest one, not just clobber over.

Closed via https://github.com/E3SM-Project/zstash/pull/115.

**Closed by golaz** 2021-02-19 22:00 UTC
