### ISSUE TITLE
Exception encountered when attempting to transfer files from HPSS

### ISSUE THREAD

**Issue by beharrop** [E3SM-Project/zstash#80] opened 2020-07-31 17:56 UTC
I have tried on a couple different dtns on Cori with multiple BGC experiments to transfer files from HPSS back to cscratch, but I continually encounter the following error message.

INFO: Transferring file from HPSS: zstash/index.db
ERROR: Transferring file from HPSS: index.db
Traceback (most recent call last):
  File "/global/cfs/cdirs/e3sm/software/anaconda_envs/base/envs/e3sm_unified_1.3.1/bin/zstash", line 8, in <module>
    sys.exit(main())
  File "/global/cfs/cdirs/e3sm/software/anaconda_envs/base/envs/e3sm_unified_1.3.1/lib/python3.7/site-packages/zstash/main.py", line 53, in main
    ls()
  File "/global/cfs/cdirs/e3sm/software/anaconda_envs/base/envs/e3sm_unified_1.3.1/lib/python3.7/site-packages/zstash/ls.py", line 39, in ls
    hpss_get(config.hpss, DB_FILENAME)
  File "/global/cfs/cdirs/e3sm/software/anaconda_envs/base/envs/e3sm_unified_1.3.1/lib/python3.7/site-packages/zstash/hpss.py", line 72, in hpss_get
    hpss_transfer(hpss, file_path, 'get', False)
  File "/global/cfs/cdirs/e3sm/software/anaconda_envs/base/envs/e3sm_unified_1.3.1/lib/python3.7/site-packages/zstash/hpss.py", line 49, in hpss_transfer
    run_command(command, error_str)
  File "/global/cfs/cdirs/e3sm/software/anaconda_envs/base/envs/e3sm_unified_1.3.1/lib/python3.7/site-packages/zstash/utils.py", line 42, in run_command
    raise Exception
Exception

I have been using the new e3sm_unified_1.3.1.  I get this exception when transferring the index.db file.  I can go in and grab transfer the index.db file manually, but I then get the same exception raised when zstash tried to transfer the first tar file from HPSS.  An example of the commands I have been trying to use, that trigger the exception:

`zstash ls --hpss=/home/s/shix/E3SM/20191204.BCRD_CNPCTC_SSP585_OIBGC.ne30_oECv3.compy/ "*.cam.h3.*"`

Anyone seen this before or is this a new bug?

**Comment by chengzhuzhang** [comment] 2020-08-04 18:12
Hi @beharrop, 

I started a transfer on cori using a bash script:

```
#!/usr/bin/env bash
umask 002

source /global/cfs/cdirs/e3sm/software/anaconda_envs/load_latest_e3sm_unified.sh

cd /global/cfs/cdirs/e3smpub/E3SM_simulations/20191204.BCRD_CNPCTC_SSP585_OIBGC.ne30_oECv3.compy
zstash extract --hpss=/home/g/golaz/2018/E3SM_simulations/repaired/20180302.DECKv1b_H3.ne30_oEC.edison archive/atm/hist/*.cam.h3.*
```
It works fine so far. On a separate note: I’m hoping to create a central place for already published e3sm data under `/e3smpub`. So individual users don’t need to extract and keep duplicated version of data on the disk. Let me know if you have some large volume of data already extracted on your scratch space and I can move them over to `/e3smpub` :)

**Comment by chengzhuzhang** [comment] 2020-08-04 18:26
@beharrop Hi, I tried the same BGC archive and reproduced the problem. However, tried on another archive, it works fine. I was wondering if this is a archive specific issue...@forsyth2 any insights?

**Comment by beharrop** [comment] 2020-08-04 18:32
Hi @chengzhuzhang , I was about to say that I had tried doing a quick `zstash ls` with one of the water cycle archives and found it to be successful like your suggestion (I am not sure why, but your previous comment isn't showing up here for me).  I tested a few other repos that I have used zstash with and again found success.  It only seems to be the BGC archives (at least the handful that I've tried) that are giving me this problem.  I have been able to successfully access these archives with `zstash extract` before, so I am not sure what has changed.  Any advice would be greatly appreciated.

Also, thanks for the e3smpub tip :).  I didn't realize that was a thing, but that is super handy.  I don't have any raw output on scratch, but I do have a number of climatologies that I made for analysis of the BGC simulations.  Would those be worth moving?

**Comment by chengzhuzhang** [comment] 2020-08-04 18:43
Got it! Try

`zstash ls --hpss=/home/s/shix/E3SM/20191204.BCRD_CNPCTC_SSP585_OIBGC.ne30_oECv3.compy/archive "*.cam.h3.*"`
it seems like the index.db is under `/archive` instead of stored at the top level. 

I'm secretly planning the e3smpub thing. Having climo's will be a plus. Haven't thought of a good structure, I will let you know once there is a concrete plan :). Thank you in advance.

**Comment by forsyth2** [comment] 2020-08-04 18:45
@chengzhuzhang I just tried that myself and it works for me.

**Comment by beharrop** [comment] 2020-08-04 19:13
Great!  That worked for me too.  Thanks for you help @chengzhuzhang , @forsyth2 .  I guess I needed to look more carefully at the HPSS directory structure.

**Comment by wenshanw** [comment] 2020-10-12 19:45
Hi,

I encountered the same error trying to list files at several different folders. Adding "archive" does not resolve it.
From globus, I see the "index.db" is just under the main folder.
Any other things I can try?

Thank you very much!

Commands I tried
`$zstash ls -l --hpss=/home/t/tang30/2019/E3SM_simulations/cori-haswell.20190611.FC5N_ne120_UV_NoUS_1r1f.conusx4v1_conusx4v1/`
`zstash ls --hpss=/home/t/tang30/2019/E3SM_simulations/cori-haswell.20190611.FC5N_ne120_UV_NoUS_1r1f.conusx4v1_conusx4v1/ "*cam*"`

ERROR msg
`INFO: Transferring file from HPSS: zstash/index.db
ERROR: Transferring file from HPSS: index.db
Traceback (most recent call last):
  File "/global/homes/w/wenshanw/.conda/envs/hpss/bin/zstash", line 8, in <module>
    sys.exit(main())
  File "/global/homes/w/wenshanw/.conda/envs/hpss/lib/python3.9/site-packages/zstash/main.py", line 53, in main
    ls()
  File "/global/homes/w/wenshanw/.conda/envs/hpss/lib/python3.9/site-packages/zstash/ls.py", line 45, in ls
    hpss_get(config.hpss, get_db_filename(cache), cache)
  File "/global/homes/w/wenshanw/.conda/envs/hpss/lib/python3.9/site-packages/zstash/hpss.py", line 72, in hpss_get
    hpss_transfer(hpss, file_path, 'get', cache, False)
  File "/global/homes/w/wenshanw/.conda/envs/hpss/lib/python3.9/site-packages/zstash/hpss.py", line 49, in hpss_transfer
    run_command(command, error_str)
  File "/global/homes/w/wenshanw/.conda/envs/hpss/lib/python3.9/site-packages/zstash/utils.py", line 42, in run_command
    raise Exception
Exception`

**Comment by chengzhuzhang** [comment] 2020-10-12 20:04
@wenshanw Hi, would you try following:
```
zstash ls --hpss=/home/t/tang30/2019/E3SM_simulations/cori-haswell.20190611.FC5N_ne120_UV_NoUS_1r1f.conusx4v1_conusx4v1 "run/*cam.h*"
```

It looks all the files are under run/ directory.

**Comment by chengzhuzhang** [comment] 2020-10-12 20:06
It appears `cori-haswell` has a `-` missing in the hpss location in your command line.

**Comment by wenshanw** [comment] 2020-10-12 21:20
Hi @chengzhuzhang, sorry, I reformatted it wrong.
In my terminal, I had the dash.
```
zstash ls --hpss=/home/t/tang30/2019/E3SM_simulations/cori-haswell.20190611.FC5N_ne120_UV_NoUS_1r1f.conusx4v1_conusx4v1 "run/*cam.h*"
```
I still got the same ERROR msg.

I am a first-time `zstash` user. I followed the instruction here: https://e3sm-project.github.io/zstash/docs/html/getting_started.html#installation-on-nersc
to install it on cori.
I am on dtn01 and zstash version v0.4.2.

**Comment by chengzhuzhang** [comment] 2020-10-12 21:32
hmmm. I just tried on Cori **login** and use the zstash installed through `e3sm-unified` as follows:
```
source /global/cfs/cdirs/e3sm/software/anaconda_envs/load_latest_e3sm_unified.sh
zstash ls --hpss=/home/t/tang30/2019/E3SM_simulations/cori-haswell.20190611.FC5N_ne120_UV_NoUS_1r1f.conusx4v1_conusx4v1 "run/*cam.h*"
```
I don't have experience with dtn01...Maybe someone else will be able to help out on this, @forsyth2 and @golaz ?

**Comment by wenshanw** [comment] 2020-10-12 21:43
weird...
I just login cori and exec these two lines of commands and got the same error msg...
```
(e3sm_unified_1.3.1.2) wenshanw@cori12:~$ which zstash
/global/cfs/cdirs/e3sm/software/anaconda_envs/base/envs/e3sm_unified_1.3.1.2/bin/zstash
```

**Comment by wenshanw** [comment] 2020-10-12 21:55
Could it be a permission issue?
But I can see the files through globus.

**Comment by forsyth2** [comment] 2020-10-12 22:27
This is puzzling. The following two lines work for me:
```
source /global/cfs/cdirs/e3sm/software/anaconda_envs/load_latest_e3sm_unified.sh
zstash ls --hpss=/home/t/tang30/2019/E3SM_simulations/cori-haswell.20190611.FC5N_ne120_UV_NoUS_1r1f.conusx4v1_conusx4v1 "run/*cam.h*"
```

I also logged into `hsi` and confirmed that `ls /home/t/tang30/2019/E3SM_simulations/cori-haswell.20190611.FC5N_ne120_UV_NoUS_1r1f.conusx4v1_conusx4v1` actually displays tar files. I can also `cd` into that directory.

@wenshanw It's failing for you on a step that I believe comes out as:`hsi -q "cd /home/t/tang30/2019/E3SM_simulations/cori-haswell.20190611.FC5N_ne120_UV_NoUS_1r1f.conusx4v1_conusx4v1; get index.db"`. This produces an `index.db` in the directory I run the command in. Does this command alone fail for you?

**Comment by forsyth2** [comment] 2020-10-12 22:28
@wenshanw Have you ever logged into `hsi` before? That might be the problem.

https://e3sm-project.github.io/zstash/docs/html/usage.html "If you have not logged into HSI before, you will have to do so before running `zstash` with HPSS. On NERSC machines, just run `hsi` on the command line and enter your credentials."

**Comment by forsyth2** [comment] 2020-10-12 22:33
I created #99 so that the next version of `zstash` will give more information than just `Exception`.

**Comment by wenshanw** [comment] 2020-10-12 23:29
> @wenshanw Have you ever logged into `hsi` before? That might be the problem.
> 
> https://e3sm-project.github.io/zstash/docs/html/usage.html "If you have not logged into HSI before, you will have to do so before running `zstash` with HPSS. On NERSC machines, just run `hsi` on the command line and enter your credentials."

Sorry, After I read through "getting started", I jumped to the examples and missed this note.
Problem solved!
Thank you very much!!!

**Comment by forsyth2** [comment] 2020-10-12 23:30
@wenshanw Glad to hear that worked!

**Closed** 2021-01-13 22:09 UTC
